export const EDIT_SCREENSHOT_SETTINGS = 'EDIT_SCREENSHOT_SETTINGS';
export const EDIT_CAMERA_SETTINGS = 'EDIT_CAMERA_SETTINGS';
export const CREATE_VIDEO = 'CREATE_VIDEO';
export const IMAGE_VIEWER = 'IMAGE_VIEWER';
